name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🖼️ Official Site'
    labels:
      - 'Official Site'
  - title: '📱 Mobile Apps'
    labels:
      - 'Mobile Apps'
  - title: '🏪 NFT Store'
    labels:
      - 'NFT Store'
  - title: '🤖 GardenBOT'
    labels:
      - 'GardenBOT'
  - title: '🧑‍🌾 Charities'
    labels:
      - 'Charities Site'
  - title: '🌐 Metaverse'
    labels:
      - 'Metaverse'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'DevOps'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION