//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinGardenWorld.Web.Localization.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoinGardenWorld.Web.Localization.Pages.Index.Resource", typeof(Index_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Flower World&quot; is a game where every single user who uses the app or takes care of at least one flower will get their own island where they can arrange and &quot;plant&quot; their real flowers in the metaverse..
        /// </summary>
        public static string _Flower_World__is_a_game_where_every_single_user_who_uses_the_app_or_takes_care_of_at_least_one_flower_will_get_their_own_island_where_they_can_arrange_and__plant__their_real_flowers_in_the_metaverse_ {
            get {
                return ResourceManager.GetString("\"Flower World\" is a game where every single user who uses the app or takes care o" +
                        "f at least one flower will get their own island where they can arrange and \"plan" +
                        "t\" their real flowers in the metaverse.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to &quot;World of Flowers&quot;, a harmonious blend of technology and nature where the digital realm meets the verdant beauty of our world. At its core, this platform offers a comprehensive Web3 infrastructure dedicated to gardening, allowing users to grow, nurture, and even earn cryptocurrency from their virtual flowers. Dive into a universe where every petal counts, and every action reverberates with the love for our planet..
        /// </summary>
        public static string _World_of_Flowers__is_a_system_equipped_with_artificial_intelligence_and_automatic_recognition_of_types_and_varieties_of_flowers_ {
            get {
                return ResourceManager.GetString("\"World of Flowers\" is a system equipped with artificial intelligence and automati" +
                        "c recognition of types and varieties of flowers.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone who takes care of at least one flower will receive a free island in the Metaverse..
        /// </summary>
        public static string Anyone_who_takes_care_of_at_least_one_flower_will_receive_a_free_island_in_the_Metaverse_ {
            get {
                return ResourceManager.GetString("Anyone who takes care of at least one flower will receive a free island in the Me" +
                        "taverse.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charities.
        /// </summary>
        public static string Charities {
            get {
                return ResourceManager.GetString("Charities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with our flower recognition bot and send him pictures of flowers, he immediately will respond with the sort of the  and information how to take care of it..
        /// </summary>
        public static string Chat_with_our_flower_recognition_bot_and_send_him_pictures_of_flowers__he_immediately_will_respond_with_the_sort_of_the__and_information_how_to_take_care_of_it_ {
            get {
                return ResourceManager.GetString("Chat with our flower recognition bot and send him pictures of flowers, he immedia" +
                        "tely will respond with the sort of the  and information how to take care of it.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Token.
        /// </summary>
        public static string Crypto_Token {
            get {
                return ResourceManager.GetString("Crypto Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even if you don&apos;t have plants, you can buy some from the NFT shop and still continue playing..
        /// </summary>
        public static string Even_if_you_don_t_have_plants__you_can_buy_some_from_the_NFT_shop_and_still_continue_playing_ {
            get {
                return ResourceManager.GetString("Even if you don\'t have plants, you can buy some from the NFT shop and still conti" +
                        "nue playing.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower Store.
        /// </summary>
        public static string Flower_Store {
            get {
                return ResourceManager.GetString("Flower Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden BOT.
        /// </summary>
        public static string Garden_BOT {
            get {
                return ResourceManager.GetString("Garden BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the app now.
        /// </summary>
        public static string Get_the_app_now {
            get {
                return ResourceManager.GetString("Get the app now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRDN token is the base currency in the entire infrastructure. All donations and causes, all rewards received for taking care of the flowers, as well as the metaverse are in the main crypto currency GRDN..
        /// </summary>
        public static string GRDN_token_is_the_base_currency_in_the_entire_infrastructure__All_donations_and_causes__all_rewards_received_for_taking_care_of_the_flowers__as_well_as_the_metaverse_are_in_the_main_crypto_currency_GRDN_ {
            get {
                return ResourceManager.GetString("GRDN token is the base currency in the entire infrastructure. All donations and c" +
                        "auses, all rewards received for taking care of the flowers, as well as the metav" +
                        "erse are in the main crypto currency GRDN.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home - World of Flowers.
        /// </summary>
        public static string Home___World_of_Flowers {
            get {
                return ResourceManager.GetString("Home - World of Flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In it, users not only grow but can also develop and sell their best photos of their most beautiful flowers. Every single photo in the system can be created as an NFT and thus either sold in the shop or used in the flower metaverse..
        /// </summary>
        public static string In_it__users_not_only_grow_but_can_also_develop_and_sell_their_best_photos_of_their_most_beautiful_flowers__Every_single_photo_in_the_system_can_be_created_as_an_NFT_and_thus_either_sold_in_the_shop_or_used_in_the_flower_metaverse_ {
            get {
                return ResourceManager.GetString("In it, users not only grow but can also develop and sell their best photos of the" +
                        "ir most beautiful flowers. Every single photo in the system can be created as an" +
                        " NFT and thus either sold in the shop or used in the flower metaverse.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Metaverse.
        /// </summary>
        public static string Login_to_Metaverse {
            get {
                return ResourceManager.GetString("Login to Metaverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metaverse.
        /// </summary>
        public static string Metaverse {
            get {
                return ResourceManager.GetString("Metaverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Application.
        /// </summary>
        public static string Mobile_Application {
            get {
                return ResourceManager.GetString("Mobile Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open platform for everyone.
        /// </summary>
        public static string Open_platform_for_everyone {
            get {
                return ResourceManager.GetString("Open platform for everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;title-dark&quot;&gt;Own the future!&lt;/span&gt; &lt;br /&gt; &lt;span&gt;&quot;World of Flowers&quot;&lt;/span&gt; &lt;span class=&quot;title-dark&quot;&gt;is your portal to the blockchain world.&lt;/span&gt;.
        /// </summary>
        public static string Own_the_future___World_of_Flowers__is_your_portal_to_the_blockchain_world_ {
            get {
                return ResourceManager.GetString("Own the future! \"World of Flowers\" is your portal to the blockchain world.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Currencies.
        /// </summary>
        public static string Supported_Currencies {
            get {
                return ResourceManager.GetString("Supported Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The donation system in &quot;World of Flowers&quot; is a unique way that users,together, can save endangered places or clear a polluted forest of waste..
        /// </summary>
        public static string The_donation_system_in__World_of_Flowers__is_a_unique_way_that_users_together__can_save_endangered_places_or_clear_a_polluted_forest_of_waste_ {
            get {
                return ResourceManager.GetString("The donation system in \"World of Flowers\" is a unique way that users,together, ca" +
                        "n save endangered places or clear a polluted forest of waste.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Metaverse can be played freely by all flower lovers..
        /// </summary>
        public static string The_Metaverse_can_be_played_freely_by_all_flower_lovers_ {
            get {
                return ResourceManager.GetString("The Metaverse can be played freely by all flower lovers.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile application for flowers.
        /// </summary>
        public static string The_mobile_application_for_flowers {
            get {
                return ResourceManager.GetString("The mobile application for flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile application is a way to identify flowers and plan their best cultivation according to their type, season and weather conditions where the flower is located..
        /// </summary>
        public static string The_mobile_application_is_a_way_to_identify_flowers_and_plan_their_best_cultivation_according_to_their_type__season_and_weather_conditions_where_the_flower_is_located_ {
            get {
                return ResourceManager.GetString("The mobile application is a way to identify flowers and plan their best cultivati" +
                        "on according to their type, season and weather conditions where the flower is lo" +
                        "cated.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile application will keep reminding you when you need to water your plants and you will never forget to leave them dry again..
        /// </summary>
        public static string The_mobile_application_will_keep_reminding_you_when_you_need_to_water_your_plants_and_you_will_never_forget_to_leave_them_dry_again_ {
            get {
                return ResourceManager.GetString("The mobile application will keep reminding you when you need to water your plants" +
                        " and you will never forget to leave them dry again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The more flowers you have in the &quot;World of Flowers&quot;, the more GRDN Coin you will earn per day if you play..
        /// </summary>
        public static string The_more_flowers_you_have_in_the__World_of_Flowers___the_more_GRDN_Coin_you_will_earn_per_day_if_you_play_ {
            get {
                return ResourceManager.GetString("The more flowers you have in the \"World of Flowers\", the more GRDN Coin you will " +
                        "earn per day if you play.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user starts their journey by downloading the flower app. Immediately after, he will be prompted to take a photo or upload a photo of the flower he wishes to add and will receive a QR code for quick information that he can use to put on the pot or to sell real flowers in a shop. The app will automatically recognize the type of flower and start reminding the user when it needs watering..
        /// </summary>
        public static string The_user_starts_their_journey_by_downloading_the_flower_app__Immediately_after__he_will_be_prompted_to_take_a_photo_or_upload_a_photo_of_the_flower_he_wishes_to_add_and_will_receive_a_QR_code_for_quick_information_that_he_can_use_to_put_on_the_pot_or_to_sell_real_flowers_in_a_shop__The_app_will_automatically_recognize_the_type_of_flower_and_start_reminding_the_user_when_it_needs_watering_ {
            get {
                return ResourceManager.GetString(@"The user starts their journey by downloading the flower app. Immediately after, he will be prompted to take a photo or upload a photo of the flower he wishes to add and will receive a QR code for quick information that he can use to put on the pot or to sell real flowers in a shop. The app will automatically recognize the type of flower and start reminding the user when it needs watering.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you take good care of your garden, let it take care of you. Go to the NFT store and sell your collection of photos of your most beautiful flower, and if you continue to take care of it, each subsequent photo will be of a higher level and that will make it more valuable..
        /// </summary>
        public static string When_you_take_good_care_of_your_garden__let_it_take_care_of_you__Go_to_the_NFT_store_and_sell_your_collection_of_photos_of_your_most_beautiful_flower__and_if_you_continue_to_take_care_of_it__each_subsequent_photo_will_be_of_a_higher_level_and_that_will_make_it_more_valuable_ {
            get {
                return ResourceManager.GetString(@"When you take good care of your garden, let it take care of you. Go to the NFT store and sell your collection of photos of your most beautiful flower, and if you continue to take care of it, each subsequent photo will be of a higher level and that will make it more valuable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌼 World of Flowers 🌺.
        /// </summary>
        public static string World_of_Flowers__with_icons_ {
            get {
                return ResourceManager.GetString("World of Flowers (with icons)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your island will grow with the number of flowers that you have. You can even add decorations to your island and invite other players to visit it..
        /// </summary>
        public static string Your_island_will_grow_with_the_number_of_flowers_that_you_have__You_can_even_add_decorations_to_your_island_and_invite_other_players_to_visit_it_ {
            get {
                return ResourceManager.GetString("Your island will grow with the number of flowers that you have. You can even add " +
                        "decorations to your island and invite other players to visit it.", resourceCulture);
            }
        }
    }
}
