//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinGardenWorldMobileApp.MobileAppTheme.Localization.Components.Menus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PwaInstallMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PwaInstallMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoinGardenWorldMobileApp.MobileAppTheme.Localization.Components.Menus.PwaInstallM" +
                            "enu", typeof(PwaInstallMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GardenAPP to Home Screen.
        /// </summary>
        internal static string Add_GardenAPP_to_Home_Screen {
            get {
                return ResourceManager.GetString("Add GardenAPP to Home Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Home Screen.
        /// </summary>
        internal static string Add_to_Home_Screen {
            get {
                return ResourceManager.GetString("Add to Home Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install GardenAPP.
        /// </summary>
        internal static string Install_GardenAPP {
            get {
                return ResourceManager.GetString("Install GardenAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install GardenAPP on your home screen, and access it just like a regular app. Open your Safari menu and tap &quot;Add to Home Screen&quot;..
        /// </summary>
        internal static string Install_GardenAPP_on_your_home_screen__and_access_it_just_like {
            get {
                return ResourceManager.GetString("Install GardenAPP on your home screen, and access it just like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install GardenAPP to your Home Screen to enjoy a unique and native experience..
        /// </summary>
        internal static string Install_GardenAPP_to_your_Home_Screen_to_enjoy {
            get {
                return ResourceManager.GetString("Install GardenAPP to your Home Screen to enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe later.
        /// </summary>
        internal static string Maybe_later {
            get {
                return ResourceManager.GetString("Maybe later", resourceCulture);
            }
        }
    }
}
