//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinGardenWorldMobileApp.MobileAppTheme.Localization.Components.Cards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TopAccountsForTheMonth {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TopAccountsForTheMonth() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoinGardenWorldMobileApp.MobileAppTheme.Localization.Components.Cards.TopAccounts" +
                            "ForTheMonth", typeof(TopAccountsForTheMonth).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Garden.
        /// </summary>
        internal static string Close_Garden {
            get {
                return ResourceManager.GetString("Close Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Gardeners:.
        /// </summary>
        internal static string Elite_Gardeners_ {
            get {
                return ResourceManager.GetString("Elite Gardeners:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flora Pioneer.
        /// </summary>
        internal static string Flora_Pioneer {
            get {
                return ResourceManager.GetString("Flora Pioneer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden Guru.
        /// </summary>
        internal static string Garden_Guru {
            get {
                return ResourceManager.GetString("Garden Guru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Maestro.
        /// </summary>
        internal static string Plant_Maestro {
            get {
                return ResourceManager.GetString("Plant Maestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Most Viewed Accounts.
        /// </summary>
        internal static string The_Most_Viewed_Accounts {
            get {
                return ResourceManager.GetString("The Most Viewed Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These distinguished members consistently share stunning photos of blossoming flowers, captivating our community with their horticultural flair..
        /// </summary>
        internal static string These_distinguished_members_consistently_share_stunning_photos_of_blossoming_flowers__captivating_our_community_with_their_horticultural_flair_ {
            get {
                return ResourceManager.GetString("These distinguished members consistently share stunning photos of blossoming flow" +
                        "ers, captivating our community with their horticultural flair.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Accounts for the Month.
        /// </summary>
        internal static string Top_Accounts_for_the_Month {
            get {
                return ResourceManager.GetString("Top Accounts for the Month", resourceCulture);
            }
        }
    }
}
