//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinGardenWorldMobileApp.MobileAppTheme.Localization.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoinGardenWorldMobileApp.MobileAppTheme.Localization.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this app, people can better understand their flowers&apos; needs and grow them more effectively..
        /// </summary>
        internal static string By_using_this_app__people_can_better_understand_their_flowers__needs_and_grow_them_more_effectively_ {
            get {
                return ResourceManager.GetString("By using this app, people can better understand their flowers\' needs and grow the" +
                        "m more effectively.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dive into a universe where every flower tells a story, and every island is a testament to the harmonious blend of nature and technology..
        /// </summary>
        internal static string Dive_into_a_universe_where_every_flower_tells_a_story__and_every_island_is_a_testament_to_the_harmonious_blend_of_nature_and_technology_ {
            get {
                return ResourceManager.GetString("Dive into a universe where every flower tells a story, and every island is a test" +
                        "ament to the harmonious blend of nature and technology.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Donations and Causes&quot; section of the World of Flowers platform introduces a groundbreaking approach to environmental conservation..
        /// </summary>
        internal static string The__Donations_and_Causes__section_of_the_World_of_Flowers_platform_introduces_a_groundbreaking_approach_to_environmental_conservation_ {
            get {
                return ResourceManager.GetString("The \"Donations and Causes\" section of the World of Flowers platform introduces a " +
                        "groundbreaking approach to environmental conservation.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app can help people learn more about the flowers in their environment and appreciate their beauty..
        /// </summary>
        internal static string This_app_can_help_people_learn_more_about_the_flowers_in_their_environment_and_appreciate_their_beauty_ {
            get {
                return ResourceManager.GetString("This app can help people learn more about the flowers in their environment and ap" +
                        "preciate their beauty.", resourceCulture);
            }
        }
    }
}
