//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinGardenWorldMobileApp.MobileAppTheme.Localization.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Walkthrough {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Walkthrough() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoinGardenWorldMobileApp.MobileAppTheme.Localization.Pages.Walkthrough", typeof(Walkthrough).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a part of.
        /// </summary>
        public static string a_part_of {
            get {
                return ResourceManager.GetString("a part of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Revolutionary Set of Apps.
        /// </summary>
        public static string a_Revolutionary_Set_of_Apps {
            get {
                return ResourceManager.GetString("a Revolutionary Set of Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with 💗 Love  and Care by.
        /// </summary>
        public static string Made_with_Love_and_Care_by {
            get {
                return ResourceManager.GetString("Made with Love and Care by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Chat Bot App uses AI technology to recognize different types of flowers and provide users with more information about them. This app can help people learn more about the flowers in their environment and appreciate their beauty..
        /// </summary>
        public static string Our_Chat_Bot_App_uses_AI_technology_to_recognize_different_types_of_flowers {
            get {
                return ResourceManager.GetString("Our Chat Bot App uses AI technology to recognize different types of flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Flower Recognition and Care App uses image recognition technology to identify different types of flowers and provides users with helpful tips on how to care for them. This app also sends notifications to remind users when it&apos;s time to water their plants. By using this app, people can better understand their flowers&apos; needs and grow them more effectively..
        /// </summary>
        public static string Our_Flower_Recognition_and_Care_App_uses_image_recognition {
            get {
                return ResourceManager.GetString("Our Flower Recognition and Care App uses image recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Exploring GardenAPP &lt;br /&gt; by &quot;World of Flowers&quot;.
        /// </summary>
        public static string Start_Exploring_GardenAPP_by_World_of_Flowers {
            get {
                return ResourceManager.GetString("Start Exploring GardenAPP by World of Flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step into the enchanting &quot;World of Flowers&quot; Metaverse, where the beauty of nature meets the limitless possibilities of the digital realm. Dive into a universe where every flower tells a story, and every island is a testament to the harmonious blend of nature and technology..
        /// </summary>
        public static string Step_into_the_enchanting__World_of_Flowers__Metaverse {
            get {
                return ResourceManager.GetString("Step into the enchanting \"World of Flowers\" Metaverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Donations and Causes&quot; section of the World of Flowers platform introduces a groundbreaking approach to environmental conservation. This unique crowdfunding system empowers individuals to take action against environmental degradation. Dive into a world where technology meets nature, and every individual has the power to make a tangible difference..
        /// </summary>
        public static string The__Donations_and_Causes__section_of_the_World_of_Flowers_platform {
            get {
                return ResourceManager.GetString("The \"Donations and Causes\" section of the World of Flowers platform", resourceCulture);
            }
        }
    }
}
