name: Deploy GardenBOT Site - Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: GardenBOT Site - Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Setup .NET SDK 6 LTS
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
     
      - name: Setup .NET SDK 7 STS
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'                            

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_ISLAND_0CA8C7D03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "src/garden-bot/CoinGardenBotCore.Web" # App source code path
          api_location: "src/garden-bot/CoinGardenBotCore.Api" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
          