# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy GardenBot Messaging API - Azure
on:
  push:
    paths:
    - 'src/garden-bot/CoinGardenBotCore/**'
    branches:
      - main
  workflow_dispatch:


env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src/garden-bot/CoinGardenBotCore/CoinGardenBotCore/CoinGardenBotCore.csproj # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.x' # set this to the dotnet version to use

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Set VERSION variable
        run: |
          echo "VERSION_CI=$(type version).${{github.run_number}}" | Out-File -FilePath $env:GITHUB_ENV -Append          

      - name: .NET project version updater - ${{ env.VERSION_CI }}
        uses: vers-one/dotnet-project-version-updater@v1.2
        with:
          file: "src/garden-bot/**/*.csproj"
          version: "${{ env.VERSION_CI }}"
          
      - name: dotnet publish
        run: dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/CoinGardenWorld.GardenBotMessagingAPI

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .gardenbot-messagingapi
          path: ${{env.DOTNET_ROOT}}/CoinGardenWorld.GardenBotMessagingAPI 


  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Azure'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .gardenbot-messagingapi
          
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'coingardenBotCore'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5C17D297D868466B91972776E122375A }}
          