# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Identity Server - Azure

on:
  push:
    paths:
    - 'src/identityserver/**'
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  PROJECT_PATH: "src/identityserver/CoinGardenWorld.IdentityServer/CoinGardenWorld.IdentityServer.csproj"
 
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Set VERSION variable
        shell: bash
        run: |
          VER=$(cat VERSION)
          VER_LONG="$VER.${{github.run_number}}"
          echo "VERSION_CI=$VER_LONG" >> $GITHUB_ENV
          
      - name: Show VERSION variable
        shell: bash
        run: |
          echo "Building version - ${{ env.VERSION_CI }}"

      - name: .NET project version updater
        # You may pin to the exact commit or the version.
        # uses: vers-one/dotnet-project-version-updater@4838bb90da42ab72f272a9dde7888c1b7fb361f1
        uses: vers-one/dotnet-project-version-updater@v1.2
        with:
          # Project file path
          file: "src/identityserver/**/*.csproj"
          # New version
          version: "${{ env.VERSION_CI }}"
          
      - name: dotnet publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/CoinGardenWorld.IdentityServer

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .identityserver
          path: ${{env.DOTNET_ROOT}}/CoinGardenWorld.IdentityServer

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Azure'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .identityserver

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'coingarden-identity'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_83446832CD6A454583C3D4FEAAC00239 }}
          package: .
